CLASS ztesing DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_oo_adt_classrun.
  METHODS FLUSH.
  METHODS FILL_DATA.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZTESING IMPLEMENTATION.


METHOD FILL_DATA.
DATA : LT_DATA TYPE TABLE OF ZEMPP.
       APPEND VALUE  #(
       key_id = '2406'
       company_name = 'WIPRO'
       STREET = 'NANAKRAMKUDA'
       CITY = 'HYD'
        ) TO LT_DATA .
        INSERT  ZEMPP FROM TABLE @LT_DATA.
ENDMETHOD.


METHOD FLUSH.
DELETE FROM : ZEMPP.
ENDMETHOD.


METHOD if_oo_adt_classrun~main.
ME->flush(  ).
ME->fill_data(  ).
ENDMETHOD.
ENDCLASS.
